// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ITEMCLASS_H_
#define FLATBUFFERS_GENERATED_ITEMCLASS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

enum ItemClass : uint8_t {
  ItemClass_system = 0,
  ItemClass_currency = 1,
  ItemClass_gem = 2,
  ItemClass_ring = 3,
  ItemClass_amulet = 4,
  ItemClass_crown = 5,
  ItemClass_key = 6,
  ItemClass_coin = 7,
  ItemClass_ore = 8,
  ItemClass_item = 9,
  ItemClass_potion = 10,
  ItemClass_ingot = 11,
  ItemClass_nugget = 12,
  ItemClass_tool = 13,
  ItemClass_weapon = 14,
  ItemClass_armor = 15,
  ItemClass_shield = 16,
  ItemClass_plant = 17,
  ItemClass_book = 18,
  ItemClass_MIN = ItemClass_system,
  ItemClass_MAX = ItemClass_book
};

inline const ItemClass (&EnumValuesItemClass())[19] {
  static const ItemClass values[] = {
    ItemClass_system,
    ItemClass_currency,
    ItemClass_gem,
    ItemClass_ring,
    ItemClass_amulet,
    ItemClass_crown,
    ItemClass_key,
    ItemClass_coin,
    ItemClass_ore,
    ItemClass_item,
    ItemClass_potion,
    ItemClass_ingot,
    ItemClass_nugget,
    ItemClass_tool,
    ItemClass_weapon,
    ItemClass_armor,
    ItemClass_shield,
    ItemClass_plant,
    ItemClass_book
  };
  return values;
}

inline const char * const *EnumNamesItemClass() {
  static const char * const names[20] = {
    "system",
    "currency",
    "gem",
    "ring",
    "amulet",
    "crown",
    "key",
    "coin",
    "ore",
    "item",
    "potion",
    "ingot",
    "nugget",
    "tool",
    "weapon",
    "armor",
    "shield",
    "plant",
    "book",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemClass(ItemClass e) {
  if (flatbuffers::IsOutRange(e, ItemClass_system, ItemClass_book)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemClass()[index];
}

#endif  // FLATBUFFERS_GENERATED_ITEMCLASS_H_
